name = "auth0-custom-domain-fetch"
main = "index.mjs"
compatibility_date = "2025-07-29"

workers_dev = false
routes = [
    { pattern = "cf-fetch.smcd.authlab.work", custom_domain = true }
]

[observability.logs]
enabled = true
